package com.medicto.medicto;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import org.w3c.dom.Text;

public class AgreementActivity extends AppCompatActivity {

    TextView textView;
    Button button,button2;
    String language;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_agreement);
        button = (Button)findViewById(R.id.activity_agreemet_button);
        button2 = (Button)findViewById(R.id.activity_agreemet_button2);
        Intent intent = getIntent();
        language = intent.getStringExtra("language");

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(getApplicationContext(),SignUpActivity.class);
                intent.putExtra("language",language);
                startActivity(intent);
                finish();
            }
        });

        button2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });

        textView = (TextView)findViewById(R.id.activity_agreement_textview);
        textView.setText("Privacy Policy\n" +
                "Effective date: July 24th, 2020 \n" +
                "\n" +
                "10LOCO Inc. (\"us\", \"we\", or \"our\") operates the MEDICTO APP mobile application (hereinafter referred to as the \"Service\").\n" +
                "\n" +
                "This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.\n" +
                "\n" +
                "We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.\n" +
                "\n" +
                "Definitions\n" +
                "Service\n" +
                "Service means the MEDICTO APP mobile application operated by 10LOCO Inc.\n" +
                "\n" +
                "Personal Data\n" +
                "Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).\n" +
                "\n" +
                "Usage Data\n" +
                "Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n" +
                "\n" +
                "Cookies\n" +
                "Cookies are small files stored on your device (computer or mobile device).\n" +
                "\n" +
                "Data Controller\n" +
                "Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.\n" +
                "\n" +
                "For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.\n" +
                "\n" +
                "Data Processors (or Service Providers)\n" +
                "Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.\n" +
                "\n" +
                "We may use the services of various Service Providers in order to process your data more effectively.\n" +
                "\n" +
                "Data Subject (or User)\n" +
                "Data Subject is any living individual who is using our Service and is the subject of Personal Data.\n" +
                "\n" +
                "Information Collection and Use\n" +
                "We collect several different types of information for various purposes to provide and improve our Service to you.\n" +
                "\n" +
                "Types of Data Collected\n" +
                "Personal Data\n" +
                "While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (\"Personal Data\"). Personally identifiable information may include, but is not limited to:\n" +
                "\n" +
                "User ID, User password\n" +
                "\n" +
                "Email address\n" +
                "\n" +
                "Cookies and Usage Data\n" +
                "\n" +
                "We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.\n" +
                "\n" +
                "Usage Data\n" +
                "We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (\"Usage Data\").\n" +
                "\n" +
                "This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, usage data of our Service, faulty usage record, and other diagnostic data.\n" +
                "\n" +
                "When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.\n" +
                "\n" +
                "Location Data\n" +
                "We may use and store information about your location and your country if you give us permission to do so (\"Location Data\"). We use this data to provide features of our Service, to improve and customize our Service.\n" +
                "\n" +
                "You can enable or disable location services when you use our Service at any time by way of your device settings.\n" +
                "\n" +
                "Tracking Cookies Data\n" +
                "We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.\n" +
                "\n" +
                "Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.\n" +
                "\n" +
                "You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.\n" +
                "\n" +
                "Examples of Cookies we use:\n" +
                "\n" +
                "Session Cookies. We use Session Cookies to operate our Service.\n" +
                "\n" +
                "Preference Cookies. We use Preference Cookies to remember your preferences and various settings.\n" +
                "\n" +
                "Security Cookies. We use Security Cookies for security purposes.\n" +
                "\n" +
                "User Payment Data\n" +
                "We may also collect and use information of payment data to establish payment for our Service(“User Payment Data”). User Payment Data may include, but is not limited to:\n" +
                "\n" +
                "Credit card company, Credit card number, Payment method, Transaction number (for credit card payment)\n" +
                "\n" +
                "Account ID, Transaction ID (for PayPal, Alipay)\n" +
                "\n" +
                "Bank name\n" +
                "\n" +
                "Account holder name, Account number\n" +
                "\n" +
                "Resident Registration number, Foreign registration number\n" +
                "\n" +
                "Mobile phone number\n" +
                "\n" +
                "Other Data\n" +
                "We may also collect and use information of other than above to promotion registration, use of specific service, use of store in our Service, etc. if you give us permission to do so.\n" +
                "\n" +
                "Use of Data\n" +
                "10LOCO Inc. uses the collected data for various purposes:\n" +
                "\n" +
                "To provide and maintain our Service commonly or privately\n" +
                "\n" +
                "To calculate fee or payment for provision or purchase of our goods or our Service\n" +
                "\n" +
                "To verify or manage user such as identification, checking intention of registration and age, prevention of faulty usage of rogue member, restriction of member who violated the terms and conditions, sanction upon disturbance of smooth operation of our Service, preservation records for dispute mediation, checking intention of membership withdrawal\n" +
                "\n" +
                "To notify you about changes to our Service\n" +
                "\n" +
                "To allow you to participate in interactive features of our Service when you choose to do so\n" +
                "\n" +
                "To provide customer support\n" +
                "\n" +
                "To gather analysis or valuable information so that we can improve our Service\n" +
                "\n" +
                "To monitor the usage of our Service\n" +
                "\n" +
                "To detect, prevent and address technical issues\n" +
                "\n" +
                "To develop new services and to use for marketing or advertise\n" +
                "\n" +
                "To refund points and to pay professional translation fee\n" +
                "\n" +
                "To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information\n" +
                "\n" +
                "Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)\n" +
                "If you are from the European Economic Area (EEA), 10LOCO Inc. legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.\n" +
                "\n" +
                "10LOCO Inc. may process your Personal Data because:\n" +
                "\n" +
                "We need to perform a contract with you\n" +
                "\n" +
                "You have given us permission to do so\n" +
                "\n" +
                "The processing is in our legitimate interests and it is not overridden by your rights\n" +
                "\n" +
                "For payment processing purposes\n" +
                "\n" +
                "To comply with the law\n" +
                "\n" +
                "Retention of Data\n" +
                "10LOCO Inc. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.\n" +
                "\n" +
                "10LOCO Inc. will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.\n" +
                "\n" +
                "Transfer of Data\n" +
                "Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.\n" +
                "\n" +
                "If you are located outside Republic of Korea and choose to provide information to us, please note that we transfer the data, including Personal Data, to Republic of Korea and process it there.\n" +
                "\n" +
                "Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.\n" +
                "\n" +
                "10LOCO Inc. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.\n" +
                "\n" +
                "Disclosure of Data\n" +
                "Business Transaction\n" +
                "If 10LOCO Inc. is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.\n" +
                "\n" +
                "Disclosure for Law Enforcement\n" +
                "Under certain circumstances 10LOCO Inc. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).\n" +
                "\n" +
                "Legal Requirements\n" +
                "10LOCO Inc. may disclose your Personal Data in the good faith belief that such action is necessary to:\n" +
                "\n" +
                "To comply with a legal obligation\n" +
                "\n" +
                "To protect and defend the rights or property of 10LOCO Inc. \n" +
                "\n" +
                "To prevent or investigate possible wrongdoing in connection with the Service\n" +
                "\n" +
                "To protect the personal safety of users of the Service or the public\n" +
                "\n" +
                "To protect against legal liability\n" +
                "\n" +
                "Security of Data\n" +
                "The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.\n" +
                "\n" +
                "Our Policy on \"Do Not Track\" Signals under the California Online Protection Act (CalOPPA)\n" +
                "We do not support Do Not Track (\"DNT\"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.\n" +
                "\n" +
                "You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.\n" +
                "\n" +
                "Your Data Protection Rights under the General Data Protection Regulation (GDPR)\n" +
                "If you are a resident of the European Economic Area (EEA), you have certain data protection rights. 10LOCO Inc. aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.\n" +
                "\n" +
                "If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.\n" +
                "\n" +
                "In certain circumstances, you have the following data protection rights:\n" +
                "\n" +
                "The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.\n" +
                "\n" +
                "The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.\n" +
                "\n" +
                "The right to object. You have the right to object to our processing of your Personal Data.\n" +
                "\n" +
                "The right of restriction. You have the right to request that we restrict the processing of your personal information.\n" +
                "\n" +
                "The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.\n" +
                "\n" +
                "The right to withdraw consent. You also have the right to withdraw your consent at any time where 10LOCO Inc. relied on your consent to process your personal information.\n" +
                "\n" +
                "Please note that we may ask you to verify your identity before responding to such requests.\n" +
                "\n" +
                "You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).\n" +
                "\n" +
                "Service Providers\n" +
                "We may employ third party companies and individuals to facilitate our Service (\"Service Providers\"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.\n" +
                "\n" +
                "These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.\n" +
                "\n" +
                "Analytics\n" +
                "We may use third-party Service Providers to monitor and analyse the use of our Service.\n" +
                "\n" +
                "Google Analytics\n" +
                "Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalise the ads of its own advertising network.\n" +
                "\n" +
                "For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en\n" +
                "\n" +
                "Behavioral Remarketing\n" +
                "10LOCO Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.\n" +
                "\n" +
                "Google Ads (AdWords)\n" +
                "Google Ads (AdWords) remarketing service is provided by Google Inc.\n" +
                "\n" +
                "You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads\n" +
                "\n" +
                "Google also recommends installing the Google Analytics Opt-out Browser Add-on - https://tools.google.com/dlpage/gaoptout - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.\n" +
                "\n" +
                "For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en\n" +
                "\n" +
                "YouTube API Service\n" +
                "YouTube API Service is provided by Google Inc. Flitto uses the YouTube API Service to access YouTube accounts and view, download, and upload caption tracks. Flitto does not use the YouTube API Service for any other purposes than those mentioned above.\n" +
                "\n" +
                "Their Terms of Service can be viewed at https://www.youtube.com/t/terms\n" +
                "\n" +
                "Google Security setting page https://security.google.com/settings/security/permissions\n" +
                "\n" +
                "User Identity Verification\n" +
                "We may verify user identity within the Service. In that case, we use third-party services for identity verification processing (e.g. identity verification processors).\n" +
                "\n" +
                "The payment processors we work with are:\n" +
                "\n" +
                "NICE Information Service Co., Ltd.\n" +
                "Their Privacy Policy (Korean only) can be viewed at http://www.niceinfo.co.kr/etc/privacy.nice\n" +
                "\n" +
                "Payments\n" +
                "We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).\n" +
                "\n" +
                "We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.\n" +
                "-----------------------------------------------------------------------------\n" +
                "The payment processors we work with are:\n" +
                "\n" +
                "Apple Store In-App Payments\n" +
                "Their Privacy Policy can be viewed at https://www.apple.com/legal/privacy/en-ww/\n" +
                "\n" +
                "Google Play In-App Payments\n" +
                "Their Privacy Policy can be viewed at https://www.google.com/policies/privacy/\n" +
                "\n" +
                "PayPal / Braintree\n" +
                "Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full\n" +
                "\n" +
                "Alipay\n" +
                "Their Privacy Policy can be viewed at https://render.alipay.com/p/f/agreementpages/alipayglobalprivacypolicy.html\n" +
                "\n" +
                "KG Inicis\n" +
                "Their Privacy Policy (Korean only) can be viewed at https://www.inicis.com/blog/archives/916\n" +
                "\n" +
                "WechatPay\n" +
                "Their Privacy Policy (Chinese only) can be viewed at https://weixin.qq.com/cgi-bin/readtemplate?lang=en_US&check=false&t=weixin_agreement&s=pay and https://www.tenpay.com/v3/helpcenter/low/privacy.shtml\n" +
                "\n" +
                "Korea Financial Telecommunications & Clearings Institute\n" +
                "Their Privacy Policy (Korean only) can be viewed at http://www.kftc.or.kr/kftc/data/EgovDataPersonInfo.do\n" +
                "\n" +
                "Sending SMS, Email, Promotion, Coupon and Commercial\n" +
                "We may send SMS, email, promotion, coupon and commercial services within the Service. In that case, we use third-party services for send processing (e.g. payment processors).\n" +
                "\n" +
                "The processors of sending SMS, email, promotion, coupon and commercial we work with are:\n" +
                "\n" +
                "WINCUBE Marketing\n" +
                "Their Privacy Policy (Korean only) can be viewed at http://www.giftting.co.kr/cust.do?method=clause\n" +
                "\n" +
                "Happy Money Inc.\n" +
                "Their Privacy Policy (Korean only) can be viewed at http://www.happymoney.co.kr/svc/treaty/privateInfo.hm\n" +
                "\n" +
                "NHN toast\n" +
                "Their Privacy Policy can be viewed at https://www.toast.com/kr/terms/privacy-policy\n" +
                "\n" +
                "Chuangshi Huaxin Technology Co., Ltd. (创世华信)\n" +
                "Their website can be viewed at https://www.ipyy.com/\n" +
                "\n" +
                "Dahan Tricom (大汉三通)\n" +
                "Their Terms and Conditions (Chinese only) can be viewed at http://www.dahantc.com/files/term.pdf\n" +
                "\n" +
                "Chuanglan 253 (创蓝253)\n" +
                "Their website can be viewed at https://www.253.com/\n" +
                "\n" +
                "Tax\n" +
                "We may deduct withholding tax(or PAYE) within the Service. In that case, we use third-party services for send processing (e.g. payment processors).\n" +
                "\n" +
                "Tax Authorities (National Tax Service and Tax Offices)\n" +
                "Their Privacy Policy (Korean only) can be viewed at https://www.hometax.go.kr/websquare/popup.html?w2xPath=/ui/pp/a/b/UTXPPABA24.xml&popupID=personalInfo&w2xHome=/ui/pp/&w2xDocumentRoot=\n" +
                "\n" +
                "Links to Other Sites\n" +
                "Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.\n" +
                "---------------------------------------------------------------------------------------\n" +
                "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.\n" +
                "\n" +
                "Children's Privacy\n" +
                "Our Service does not address anyone under the age of 18 (\"Children\").\n" +
                "\n" +
                "We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.\n" +
                "\n" +
                "Changes to This Privacy Policy\n" +
                "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.\n" +
                "\n" +
                "We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the \"effective date\" at the top of this Privacy Policy.\n" +
                "\n" +
                "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.\n" +
                "\n" +
                "Contact Us\n" +
                "If you have any questions about this Privacy Policy, please contact us:\n" +
                "\n" +
                "By email: 10loco.official@gmail.com\n\n\n\n\n\n\n\n\n\n\n");
    }
}